import React, { createContext, useContext, useState, useEffect } from 'react'

// Language Context
interface LanguageContextType {
  language: 'sl' | 'en' | 'de' | 'it'
  setLanguage: (lang: 'sl' | 'en' | 'de' | 'it') => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'sl' | 'en' | 'de' | 'it'>('sl')

  // Translation object
  const translations = {
    sl: {
      // Navigation
      'nav.home': 'Domov',
      'nav.about': 'O nas',
      'nav.suites': 'Suite',
      'nav.activities': 'Aktivnosti',
      'nav.gallery': 'Galerija',
      'nav.contact': 'Kontakt',
      'nav.reservation': 'Rezervacija',
      'nav.admin': 'Admin',
      'nav.giftVoucher': 'Darilni bon',
      'nav.wellness': 'Wellness',

      // Gift Voucher
      'giftVoucher.title': 'Darilni bon',
      'giftVoucher.subtitle': 'Podarite nepozabno doživetje ob jezeru Bled',
      'giftVoucher.howItWorks': 'Kako deluje?',
      'giftVoucher.step1': 'Izberete znesek in temo bona',
      'giftVoucher.step2': 'Vnesete podatke o prejemniku',
      'giftVoucher.step3': 'Prejmete potrdilo, bon pa je dostavljen prejemniku',
      'giftVoucher.step4': 'Prejemnik rezervira bivanje z vašim bonom',
      'giftVoucher.validity': 'Darilni boni veljajo 12 mesecev od nakupa.',

      // Hero section
      'hero.title': 'Villa Adora',
      'hero.subtitle': 'Luksuzni hotel ob jezeru Bled',
      'hero.description': 'Doživite nepozabno bivanje v našem luksuznem hotelu ob čudovitem jezeru Bled',
      'hero.book': 'Rezerviraj',
      'hero.learn': 'Več informacij',
      
      // About section
      'about.title': 'O nas',
      'about.subtitle': 'Villa Adora',
      'about.description': 'Villa Adora je edinstven luksuzni hotel na obali čudovitega jezera Bled v Sloveniji. Ponuja popolno kombinacijo naravne lepote, udobja in vrhunske storitve za nepozabno bivanje.',
        // Suites section
      'suites.title': 'Luksuzne suite',
      'suites.princess.title': 'Princess Suite',
      'suites.princess.description': 'Zelo lepo opremljena in okusno dekorirana suite, v kateri se boste počutili posebno. 55 m² prijetnega prostora z bivalnim delom, spalnico in kopalnico. Stolpič nudi pogled na čudovito Blejsko jezero.',
      'suites.luxury.title': 'Luxury Suite',
      'suites.luxury.description': 'Razkošna suite, zasnovana za vrhunsko udobje in eleganco z nepozabnim razgledom na jezero.',
      'suites.penthouse.title': 'Penthouse Suite',
      'suites.penthouse.description': 'Najbolj edinstven prostor v naši hiši, razporejen v dveh nadstropjih (60 m²). Vzdušje je posebno in domače, razgledi pa dih jemajoči.',
      'suites.swan.title': 'Swan Suite',
      'suites.swan.description': 'Elegantna in prostorna suite, ki ponuja popolno zavetje za vaš oddih.',
      'suites.island.title': 'Island Suite',
      'suites.island.description': 'Stilska in luksuzna suite (65 m²) v prvem nadstropju. Nudi osupljiv razgled na jezero in Blejski otok. Ima dve luksuzni spalnici, velik bivalni del in dva balkona.',
      'suites.prestige.title': 'Prestige Suite',
      'suites.prestige.description': 'Absolutna harmonija umetniškega dekorja in prostornosti (72 m²). Nahaja se v pritličju in ponuja nepozaben razgled na jezero skozi vsa okna.',
      
      // Activities section
      'activities.title': 'Aktivnosti in doživetja',
      'activities.lake.title': 'Jezerske aktivnosti',
      'activities.lake.description': 'Pustolovščine na jezeru Bled: vožnja s čolnom do otoka, kajak, sup, ribolov in piknik na vodi.',
      'activities.mountain.title': 'Gorski pohodi',
      'activities.mountain.description': 'Raziskujte čudovite gorske poti okoli Bleda. Obiščite Ojstrico, planinske koče in uživajte v spektakularnih razgledih.',
      'activities.culinary.title': 'Kulinarične doživetje',
      'activities.culinary.description': 'Okusite lokalne specialitete v našem hotelu ali obiščite tradicionalne gostilne. Uživajte v kremni rezini in lokalnih vinih.',
      'activities.spa.title': 'Spa in relaksacija',
      'activities.spa.description': 'Sprostite se v našem luksuznem wellness centru z masažami, savno in pogledom na jezero.',
      'activities.culture.title': 'Kulturne znamenitosti',
      'activities.culture.description': 'Obiščite Blejski grad, cerkev na otoku, Vintgar sotesko in številne muzeje. Bled je poln zgodovine in kulture.',
      'activities.romantic.title': 'Romantična doživetja',
      'activities.romantic.description': 'Večerja ob sončnem zahodu, vožnja s čolnom na otok, masaža za par in kremsnita ob zvokih klavirja. Popolno za pare.',
      'activities.winter.title': 'Zimske aktivnosti',
      'activities.winter.description': 'Smučanje v Krvavcu in Voku, smučarski tek na Planici, sankanje, drsanje na jezeru in božična tržnica v Bledu.',
      'activities.adventure.title': 'Pustolovska doživetja',
      'activities.adventure.description': 'Kanjoning v Bohinju, rafting na Soči, zipline nad Vintgarjem in gorsko kolesarjenje v Triglavskem narodnem parku.',
      
      // Gallery section
      'gallery.title': 'Fotogalerija',
      'gallery.subtitle': 'Ujel dušo Villa Adore',
      'gallery.followUs': 'Sledite naši zgodbi na Instagramu',
      'gallery.followDesc': 'Za najboljše fotografije in trenutke iz Villa Adore',
      'gallery.filter.all': 'Vse',
      'gallery.filter.exterior': 'Zunanjost',
      'gallery.filter.suites': 'Suite',
      'gallery.filter.lake': 'Jezero',
      'gallery.filter.dining': 'Gostinstvo',
      'gallery.img.villa': 'Zgodovinska dediščina vile',
      'gallery.img.princess': 'Princess Suite',
      'gallery.img.prestige': 'Prestige Suite Terasa',
      'gallery.img.lakeMorning': 'Jezero Bled zjutraj',
      'gallery.img.penthouse': 'Penthouse pogled',
      'gallery.img.gardens': 'Vrtovi vile',
      'gallery.img.alpine': 'Alpska mirnost',
      'gallery.img.luxuryDetails': 'Luksuzni detajli',
      'gallery.img.dining': 'Vrhunska kulinarika',
      'gallery.img.cuisine': 'Lokalna kuhinja',
      'gallery.img.facade': 'Fasada vile',
      'gallery.img.sunset': 'Sončni zahod',
      'gallery.img.suiteInterior': 'Notranjost suite',
      'gallery.img.terrace': 'Jezerska terasa',
      'gallery.img.islandView': 'Pogled na otok',
      'gallery.img.evening': 'Večerno vzdušje',
      
      // Contact section
      'contact.title': 'Lokacija in kontakt',
      'contact.address': 'Cesta svobode 35, 4260 Bled, Slovenija',
      'contact.phone': '+386 51 603 858',
      'contact.email': 'evita.vilebled@gmail.com',
      'contact.hours': '7:00 - 22:00',
      
      // Reservation section
      'reservation.title': 'Rezervacija',
      'reservation.firstName': 'Ime',
      'reservation.lastName': 'Priimek',
      'reservation.email': 'E-pošta',
      'reservation.phone': 'Telefon',
      'reservation.checkIn': 'Datum prihoda',
      'reservation.checkOut': 'Datum odhoda',
      'reservation.adults': 'Število odraslih',
      'reservation.roomType': 'Tip sobe',
      'reservation.requests': 'Posebne zahtevke',
      'reservation.submit': 'Pošlji rezervacijo',
      
      // Nearby Attractions
      'nearby.island.title': 'Blejski otok',
      'nearby.island.description': 'Slovenska ikona — majhen otok s cerkvico, dostopen s tradicionalnim čolnom "pletna".',
      'nearby.castle.title': 'Blejski grad',
      'nearby.castle.description': 'Srednjeveški grad na kotu s panoramskim razgledom na jezero in okolico.',
      'nearby.vintgar.title': 'Vintgar',
      'nearby.vintgar.description': 'Čudovita soteska z železniškim mostom in rečnim kanjonom. Priljubljena naravna znamenitost.',
      'nearby.triglav.title': 'Triglavski narodni park',
      'nearby.triglav.description': 'Eden najstarejših narodnih parkov v Evropi. Triglav, najvišja gora Slovenije.',
      'nearby.ljubljana.title': 'Ljubljana',
      'nearby.ljubljana.description': 'Čudovito glavno mesto Slovenije z baročno arhitekturo in živahno kulturno sceno.',
      'nearby.planica.title': 'Planica',
      'nearby.planica.description': 'Svetovno priljubljena skakalnica in center zimskih športov.',
      
      // Seasonal Offers
      'offers.spring.title': 'Pomladanski paket',
      'offers.spring.desc': '3 nočitve + kajak na jezeru. Od €690.',
      'offers.summer.title': 'Poletni luksuz',
      'offers.summer.desc': '5 nočitve, 2. nočitev brezplačna. Velja julij–avgust.',
      'offers.autumn.title': 'Jesenski oddih',
      'offers.autumn.desc': '4 nočitve + degustacija vin. Od €890.',
      'offers.winter.title': 'Zimsko čudo',
      'offers.winter.desc': '3 nočitve + wellness paket. Od €750.',

      // Special Offers (detailed)
      'offers.earlyBird.title': 'Early Bird Popust',
      'offers.earlyBird.description': 'Rezervirajte 60+ dni vnaprej in prejmite 10% popust na vaše bivanje.',
      'offers.earlyBird.price': '10% popust',
      'offers.earlyBird.tag': 'Priporočamo',
      'offers.romantic.title': 'Romantični paket',
      'offers.romantic.description': '3 nočitve + šampanjec + masaža za par + večerja ob sončnem zahodu.',
      'offers.romantic.price': 'Od €890',
      'offers.romantic.tag': 'Romantika',
      'offers.wellness.title': 'Wellness umik',
      'offers.wellness.description': '3 nočitve + dnevna joga + 2 masaži + zdrav zajtrk.',
      'offers.wellness.price': 'Od €750',
      'offers.wellness.tag': 'Wellness',
      'offers.stay5.title': '5 nočitev, plačate 4',
      'offers.stay5.description': 'Rezervirajte 5 nočitev v visoki sezoni (jul-avg) in plačate samo 4.',
      'offers.stay5.price': '1 nočitev brezplačno',
      'offers.stay5.tag': 'Najbolja ponudba',
      'offers.direct.title': 'Direktna rezervacija',
      'offers.direct.description': 'Rezervirajte direktno preko naše spletne strani in prejmite brezplačno nadgradnjo sobe + pijačo dobrodošlice.',
      'offers.direct.price': 'Brezplačna nadgradnja',
      'offers.direct.tag': 'Ekskluzivno',
      'offers.lastMinute.title': 'Last Minute',
      'offers.lastMinute.description': 'Rezervirajte v zadnjih 7 dneh in prejmite 15% popust (odvisno od razpoložljivosti).',
      'offers.lastMinute.price': '15% popust',
      'offers.lastMinute.tag': 'Hitra ponudba',
      
      // Common
      'common.book': 'Rezerviraj',
      'common.learn': 'Več',
      'common.close': 'Zapri',
      'common.loading': 'Nalaganje...',
      'common.error': 'Napaka',
      'common.success': 'Uspeh',
      'common.from': 'Od',
      'common.perNight': 'na noč',
      
      // Footer
      'footer.description': 'Luksuzni butični hotel v osrčju Bleda. Zgodovinska vila iz leta 1878, preoblikovana v zatočišče elegance.',
      'footer.contact': 'Kontakt',
      'footer.links': 'Povezave',
      'footer.newsletter.title': 'E-novice',
      'footer.newsletter.desc': 'Prijavite se na naše e-novice za ekskluzivne ponudbe.',
      'footer.newsletter.placeholder': 'Vaš e-naslov',
      'footer.newsletter.button': 'Prijava',
      'footer.rights': 'Vse pravice pridržane.',

      // Why Choose Us
      'whyChoose.badge': 'Zakaj izbrati nas',
      'whyChoose.title': 'Zakaj Villa Adora?',
      'whyChoose.subtitle': 'Odkrijte, kaj nas loči od drugih in zakaj gostje iz vsega sveta prihajajo nazaj.',
      'whyChoose.bestPrice': 'Najboljša cena',
      'whyChoose.bestPriceDesc': 'Zagotavljamo najboljšo ceno. Če najdete cenejšo ponudbo, jo bomo znižali še za 10%.',
      'whyChoose.heritage': 'Zgodovinska dediščina',
      'whyChoose.heritageDesc': 'Vila iz leta 1878, obnovljena z ljubeznijo do detajlov in spoštovanjem do zgodovine.',
      'whyChoose.personalized': 'Osebna storitev',
      'whyChoose.personalizedDesc': 'Vsak gost je za nas poseben. Prilagodimo vaše bivanje do najmanjših detajlov.',
      'whyChoose.awards': 'Nagrajena kakovost',
      'whyChoose.awardsDesc': 'Priznani od gostov in potovalnih strokovnjakov kot eden najboljših butičnih hotelov v Sloveniji.',
      'whyChoose.concierge': '24/7 Concierge',
      'whyChoose.conciergeDesc': 'Naš digitalni concierge Luka je na voljo 24 ur na dan, 7 dni v tednu.',
      'whyChoose.location': 'Lokacija',
      'whyChoose.locationDesc': 'Neposredno ob jezeru Bled, s pogledom na otok in grad. Najlepša lokacija v Bledu.',
      'whyChoose.stat.rating': 'Povprečna ocena',
      'whyChoose.stat.reviews': 'Gostinskih mnenj',
      'whyChoose.stat.established': 'Ustanovljena',
      'whyChoose.stat.returnGuests': 'Gostov se vrača',

      // Seasonal Highlights
      'seasonal.badge': 'Sezonske ponudbe',
      'seasonal.title': 'Ta sezona v Vili Adora',
      'seasonal.subtitle': 'Ekskluzivni paketi za nepozabno bivanje. Rezervirajte direktno za najboljše cene.',
      'seasonal.spring.title': 'Pomladanski prebujenje',
      'seasonal.spring.desc': '3 nočitve + kajak na jezeru + voden sprehod. Cvetoče češnje in sveži alpski zrak.',
      'seasonal.spring.badge': 'Pomlad',
      'seasonal.summer.title': 'Poletni luksuzni pobeg',
      'seasonal.summer.desc': '5 nočitev, 2. nočitev brezplačno. Kopanje v jezeru, večerja na terasi in zahod sonca.',
      'seasonal.summer.badge': 'Poletje',
      'seasonal.wellness.title': 'Wellness umik',
      'seasonal.wellness.desc': '3 nočitve + dnevna joga + 2 masaži + zdrav zajtrk. Pomladite telo in dušo.',
      'seasonal.wellness.badge': 'Wellness',
      'seasonal.nights': 'nočitev',
      'seasonal.validUntil': 'Velja do',
      'seasonal.bookNow': 'Rezerviraj',
      'seasonal.viewAllOffers': 'Vse ponudbe',

      // Bled Seasons
      'seasons.title': 'Bled skozi leto',
      'seasons.subtitle': 'Vsako sezono ponuje svoja čuda',
      'seasons.spring.title': 'Pomlad',
      'seasons.spring.desc': 'Cvetoče češnje, tople sončne dni in mirno jezero. Idealno za kajak in pohodništvo.',
      'seasons.summer.title': 'Poletje',
      'seasons.summer.desc': 'Topla voda za kopanje, živahna terasa in dolgi večeri. Padajoče cvetje in lokalne specialitete.',
      'seasons.autumn.title': 'Jesen',
      'seasons.autumn.desc': 'Zlatorumena lista, čista vina in mistični megleni jutri. Popoln za romantičen oddih.',
      'seasons.winter.title': 'Zima',
      'seasons.winter.desc': 'Zavito v sneg, Bled postane pravljica. Božična tržnica, smučanje in topli napitki.',

      // Culinary & Dining
      'culinary.subtitle': 'Kulinarična doživetja',
      'culinary.title': 'Okusi Bleda',
      'culinary.description': 'Odkrijte bogastvo lokalnih okusov, ki jih ponujamo v našem hotelu. Od tradicionalne kremne rezine do vrhunskih slovenskih vin.',
      'culinary.breakfast.title': 'Zajtrk ob jezeru',
      'culinary.breakfast.description': 'Začnite dan z bogatim samopostrežnim zajtrkom na terasi s pogledom na jezero. Sveže pecivo, lokalni sirji, domači džemi in sezonsko sadje.',
      'culinary.restaurant.title': 'Gostilna 1878',
      'culinary.restaurant.description': 'Naša restavracija ponuja sodobno interpretacijo slovenske kuhane z lokalnimi sestavinami. Degustacijski meniji s priporočenimi vini.',
      'culinary.terrace.title': 'Jezerska terasa',
      'culinary.terrace.description': 'Pijte kavo ali večerjo na naši ekskluzivni terasi neposredno ob jezeru. Nepozabno doživetje ob sončnem zahodu.',
      'culinary.experiences.title': 'Kulinarične delavnice',
      'culinary.experiences.description': 'Pridružite se našim kuharskim delavnicam — naučite se pripravljati kremno rezino, tradicionalno potico ali okusiti najboljša slovenska vina.',
      'culinary.cta': 'Rezerviraj mizo',

      // Newsletter
      'newsletter.title': 'Ostanite v stiku',
      'newsletter.description': 'Prijavite se na naše e-novice in prejmite ekskluzivne ponudbe, sezonske pakete in novice iz Villa Adore.',
      'newsletter.placeholder': 'Vaš e-naslov',
      'newsletter.button': 'Prijava',
      'newsletter.success': 'Hvala za prijavo! Prejeli ste potrditveno e-pošto.',
      'newsletter.error': 'Prosimo, vnesite veljaven e-naslov.',
      'newsletter.privacy': 'Vaš e-naslov bo uporabljen izključno za naše novice. Odjavite se lahko kadarkoli.',

      // FAQ
      'faq.checkin.question': 'Kateri so časi prihoda in odhoda?',
      'faq.checkin.answer': 'Prihod (check-in) je od 15:00 do 22:00. Odhod (check-out) je do 11:00. Pozen prihod in pozen odhod sta na voljo na zahtevo — obvestite nas vnaprej.',
      'faq.cancellation.question': 'Kakšna je politika odpovedi?',
      'faq.cancellation.answer': 'Brezplačna odpoved je možna do 48 ur pred prihodom. Odpovedi v roku 48 ur pred prihodom se zaračuna prva nočitev. Pri rezervacijah v visoki sezoni (julij-avgust) velja odpoved do 72 ur pred prihodom.',
      'faq.parking.question': 'Ali je na voljo brezplačno parkiranje?',
      'faq.parking.answer': 'Da, brezplačno zasebno parkirišče je na voljo na lokaciji za vse goste. Parkiranje je varovano in pod nadzorom kamere.',
      'faq.pets.question': 'Ali so dovoljeni hišni ljubljenčki?',
      'faq.pets.answer': 'Da, hišni ljubljenčki so dovoljeni na zahtevo. Prosimo, da nas obvestite vnaprej. Dodatna pristojbina za čiščenje znaša €30 na bivanje.',
      'faq.breakfast.question': 'Ali je zajtrk vključen v ceno?',
      'faq.breakfast.answer': 'Da, bogat samopostrežni zajtrk je vključen v ceno nočitve. Zajtrk je serviran od 7:30 do 10:30 na terasi s pogledom na jezero. Na voljo so tudi veganske in glutenske opcije.',
      'faq.airport.question': 'Kako prletim iz letališča do Villa Adore?',
      'faq.airport.answer': 'Letališče Jože Pučnik Ljubljana je oddaljeno 35 km (približno 30 min vožnje). Ponujamo prevoz iz letališča po naroku (€40 enosmerno). Tudi letališče Klagenfurt (Avstrija) je oddaljeno 70 km.',
      'faq.wifi.question': 'Ali je na voljo brezplačen WiFi?',
      'faq.wifi.answer': 'Da, brezplačen visokohitrostni WiFi je na voljo v celotnem hotelu in vseh suitah. Povezava je zanesljiva tudi na terasi in v vrtnem delu.',
      'faq.spa.question': 'Ali imate wellness center?',
      'faq.spa.answer': 'Da, naš wellness center vključuje finsko savno, turško kopel in masažne storitve. Wellness je na voljo brezplačno vsem gostom. Masaže je potrebno rezervirati vnaprej.',
      'faq.transport.question': 'Ali ponujate prevoz ali izposojo koles?',
      'faq.transport.answer': 'Da, ponujamo brezplačno izposojo gorskih koles za vse goste. Ponujamo tudi prevoz z električnim vozilom po Bledu in okolici. Za daljše izlete (Vintgar, Triglavski narodni park) organiziramo prevoz po naroku.',
      'faq.miniBar.question': 'Ali ima suite minibar?',
      'faq.miniBar.answer': 'Da, vsa suite imajo minibar z izbranimi slovenskimi vinami, pijačami in prigrizki. Vsebuje tudi kavo, čaj in vročo čokolado za pripravo.',

      // Virtual Tour
      'virtualTour.lobby.title': 'Lobby & Recepcija',
      'virtualTour.lobby.description': 'Doživite veličastni vhod Villa Adore z njeno zgodovinskim šarmom in elegantno recepcijo.',
      'virtualTour.suite.title': 'Ogled luksuzne suite',
      'virtualTour.suite.description': 'Vstopite v naše signature suite in raziskujte vsak detajl luksuzne notranjosti.',
      'virtualTour.lake.title': 'Jezerska terasa',
      'virtualTour.lake.description': 'Uživajte v dih jemajočih panoramskih razgledih na Blejsko jezero z naše ekskluzivne terase.',
      'virtualTour.dining.title': 'Restavracija & Kulinarika',
      'virtualTour.dining.description': 'Odkrijte našo elegantno restavracijo in kulinarično doživetje ob jezeru.',

      // Book Direct Benefits
      'bookDirect.badge': 'Rezervirajte direktno in prihranite',
      'bookDirect.title': 'Zakaj rezervirati direktno pri nas?',
      'bookDirect.subtitle': 'Preskočite posrednike in pridobite najboljšo vrednost, ko rezervirate direktno prek naše spletne strani.',
      'bookDirect.bestPrice.title': 'Zagotovljeno najboljša cena',
      'bookDirect.bestPrice.description': 'Če najdete nižjo ceno drugje, se bomo prilagodili. Plus dodatni 5% popust za direktno rezervacijo.',
      'bookDirect.freeBreakfast.title': 'Brezplačen zajtrk',
      'bookDirect.freeBreakfast.description': 'Uživajte v bogatem samopostrežnem zajtrku s pogledom na jezero — brezplačno vključeno pri direktni rezervaciji (vrednost €25 na osebo).',
      'bookDirect.freeWifi.title': 'Premium WiFi',
      'bookDirect.freeWifi.description': 'Visokohitrostno fiber internetno omrežje po celotnem objektu, idealno za delo na daljavo ali streaming.',
      'bookDirect.upgrade.title': 'Brezplačna nadgradnja sobe',
      'bookDirect.upgrade.description': 'Glede na razpoložljivost imajo direktne rezervacije prednost pri brezplačni nadgradnji sobe.',
      'bookDirect.directSupport.title': 'Direktna podpora',
      'bookDirect.directSupport.description': 'Govorite direktno z našo ekipo za osebno storitev, posebne zahteve in lokalna priporočila.',
      'bookDirect.flexible.title': 'Fleksibilna odpoved',
      'bookDirect.flexible.description': 'Brezplačna odpoved do 48 ur pred prihodom — bolj fleksibilno kot pri rezervacijah prek tretjih strani.',
      'bookDirect.cta': 'Preveri razpoložljivost',

      // Trust Badges
      'trust.secureBooking': 'Varna rezervacija',
      'trust.noPrepayment': 'Brez predplačila',
      'trust.ssl': 'SSL šifriranje',
      'trust.bestPrice': 'Najboljša cena',

      // Wellness Preview
      'wellness.sauna.title': 'Finska savna',
      'wellness.sauna.desc': 'Topla savna z lesnim pridihom in pogledom na jezero. Pripravite se na popolno relaksacijo v naši ekskluzivni finski savni.',
      'wellness.turkish.title': 'Turška kopel',
      'wellness.turkish.desc': 'Tradicionalna turška kopel za popolno relaksacijo. Topla para in čiščenje kože v udobju galerije s pogledom na jezero.',
      'wellness.massage.title': 'Masaže',
      'wellness.massage.desc': 'Profesionalne masaže pri terapeutu — aromaterapevtske, športne in relaksacijske. Vsaka masaža je prilagojena vašim potrebam.',
      'wellness.relaxation.title': 'Sprostitvenacona',
      'wellness.relaxation.desc': 'Mirna cona za branje, meditacijo in sprostitev s pogledom na jezero. Na voljo so tudi relaksacijske sedežne prevleke in zvodna terapija.',
      'wellness.infinity.title': 'Infinity bazen',
      'wellness.infinity.desc': 'Zunanji bazen s pogledom na jezero in navezavo na zvezde. Topla voda skozi celotno leto.',
    },
    en: {
      // Navigation
      'nav.home': 'Home',
      'nav.about': 'About',
      'nav.suites': 'Suites',
      'nav.activities': 'Activities',
      'nav.gallery': 'Gallery',
      'nav.contact': 'Contact',
      'nav.reservation': 'Reservation',
      'nav.giftVoucher': 'Gift Voucher',
      'nav.admin': 'Admin',

      // Gift Voucher
      'giftVoucher.title': 'Gift Voucher',
      'giftVoucher.subtitle': 'Give the gift of an unforgettable experience on Lake Bled',
      'giftVoucher.howItWorks': 'How It Works',
      'giftVoucher.step1': 'Choose amount and theme',
      'giftVoucher.step2': 'Enter recipient details',
      'giftVoucher.step3': 'You receive confirmation, voucher is delivered to recipient',
      'giftVoucher.step4': 'Recipient redeems voucher for their stay',
      'giftVoucher.validity': 'Gift vouchers are valid for 12 months from purchase.',

      // Hero section
      'hero.title': 'Villa Adora',
      'hero.subtitle': 'Luxury Boutique Hotel Bled',
      'hero.description': 'Experience the pinnacle of elegance in our historic villa on the shores of Lake Bled.',
      'hero.book': 'Book Now',
      'hero.learn': 'Explore Villa',
      
      // About section
      'about.title': 'About Us',
      'about.subtitle': 'Villa Adora',
      'about.description': 'Villa Adora is a heritage-protected historic villa built in 1878, meticulously renovated into a boutique luxury design hotel. Located directly on the shore of Lake Bled, it offers an intimate and high-end experience.',
      
      // Suites section
      'suites.title': 'Our Luxury Suites',
      'suites.princess.title': 'Princess Suite',
      'suites.princess.description': 'Very nicely furnished and tastefully decorated suite (55 m²) with a living area, bedroom, and bathroom. The little tower overlooks beautiful Lake Bled.',
      'suites.luxury.title': 'Luxury Suite',
      'suites.luxury.description': 'Designed for ultimate comfort and elegance with unforgettable lake views.',
      'suites.penthouse.title': 'Penthouse Suite',
      'suites.penthouse.description': 'The most unique space in our house, designed with great taste across two floors (60 m²). Cozy atmosphere with breathtaking views.',
      'suites.swan.title': 'Swan Suite',
      'suites.swan.description': 'An elegant and spacious suite providing the perfect sanctuary for your stay.',
      'suites.island.title': 'Island Suite',
      'suites.island.description': 'A stylish luxury suite (65 m²) on the first floor. Offers stunning views of the lake and Bled Island. Features two bedrooms and two balconies.',
      'suites.prestige.title': 'Prestige Suite',
      'suites.prestige.description': 'Absolute harmony of artful decor and spaciousness (72 m²). Located on the ground floor with lake views from every window.',
      
      // Activities section
      'activities.title': 'Activities & Experiences',
      'activities.lake.title': 'Lake Activities',
      'activities.lake.description': 'Lake Bled adventures: rowing to the island, kayaking, stand-up paddleboarding, fishing and lakeside picnics.',
      'activities.mountain.title': 'Mountain Hiking',
      'activities.mountain.description': 'Explore the magnificent mountain trails around Bled. Visit Ojstrica, mountain huts and enjoy spectacular panoramic views.',
      'activities.culinary.title': 'Culinary Experiences',
      'activities.culinary.description': 'Taste local specialties at our hotel or visit traditional restaurants. Enjoy cream cake and local wines.',
      'activities.spa.title': 'Spa & Relaxation',
      'activities.spa.description': 'Relax in our luxury wellness center with massages, sauna and lake views.',
      'activities.culture.title': 'Cultural Heritage',
      'activities.culture.description': 'Visit Bled Castle, the island church, Vintgar Gorge, and numerous museums. Bled is steeped in history and culture.',
      'activities.romantic.title': 'Romantic Experiences',
      'activities.romantic.description': 'Sunset dinner, boat ride to the island, couples massage, and cream cake with piano music. Perfect for couples.',
      'activities.winter.title': 'Winter Activities',
      'activities.winter.description': 'Skiing in Krvavec and Voklo, ski jumping at Planica, sledding, ice skating on the lake, and the Bled Christmas market.',
      'activities.adventure.title': 'Adventure Experiences',
      'activities.adventure.description': 'Canyoning in Bohinj, rafting on the Soča River, zipline over Vintgar, and mountain biking in Triglav National Park.',
      
      // Gallery section
      'gallery.title': 'Photo Gallery',
      'gallery.subtitle': 'Capturing the soul of Villa Adora',
      'gallery.followUs': 'Follow our story on Instagram',
      'gallery.followDesc': 'For the best photos and moments from Villa Adora',
      'gallery.filter.all': 'All',
      'gallery.filter.exterior': 'Exterior',
      'gallery.filter.suites': 'Suites',
      'gallery.filter.lake': 'Lake',
      'gallery.filter.dining': 'Dining',
      'gallery.img.villa': 'Historic Heritage Villa',
      'gallery.img.princess': 'Princess Suite',
      'gallery.img.prestige': 'Prestige Suite Terrace',
      'gallery.img.lakeMorning': 'Lake Bled Morning',
      'gallery.img.penthouse': 'Penthouse View',
      'gallery.img.gardens': 'Villa Gardens',
      'gallery.img.alpine': 'Alpine Serenity',
      'gallery.img.luxuryDetails': 'Luxury Details',
      'gallery.img.dining': 'Fine Dining',
      'gallery.img.cuisine': 'Local Cuisine',
      'gallery.img.facade': 'Villa Facade',
      'gallery.img.sunset': 'Lake Sunset',
      'gallery.img.suiteInterior': 'Suite Interior',
      'gallery.img.terrace': 'Lakeside Terrace',
      'gallery.img.islandView': 'Island View',
      'gallery.img.evening': 'Evening Ambiance',
      
      // Contact section
      'contact.title': 'Location & Contact',
      'contact.address': 'Cesta svobode 35, 4260 Bled, Slovenia',
      'contact.phone': '+386 51 603 858',
      'contact.email': 'evita.vilebled@gmail.com',
      'contact.hours': '7:00 - 22:00',
      
      // Reservation section
      'reservation.title': 'Reservation',
      'reservation.firstName': 'First Name',
      'reservation.lastName': 'Last Name',
      'reservation.email': 'Email',
      'reservation.phone': 'Phone',
      'reservation.checkIn': 'Check-in Date',
      'reservation.checkOut': 'Check-out Date',
      'reservation.adults': 'Number of Adults',
      'reservation.roomType': 'Room Type',
      'reservation.requests': 'Special Requests',
      'reservation.submit': 'Submit Reservation',
      
      // Nearby Attractions
      'nearby.island.title': 'Bled Island',
      'nearby.island.description': 'Slovenia\'s iconic island with a picturesque church, accessible by traditional "pletna" wooden boat.',
      'nearby.castle.title': 'Bled Castle',
      'nearby.castle.description': 'Medieval castle on a cliff with panoramic views of the lake and surrounding Alps.',
      'nearby.vintgar.title': 'Vintgar Gorge',
      'nearby.vintgar.description': 'Stunning 1.6km gorge with boardwalks, waterfalls, and a historic railway bridge.',
      'nearby.triglav.title': 'Triglav National Park',
      'nearby.triglav.description': 'One of Europe\'s oldest national parks. Home to Mount Triglav, Slovenia\'s highest peak.',
      'nearby.ljubljana.title': 'Ljubljana',
      'nearby.ljubljana.description': 'Charming capital of Slovenia with baroque architecture, a vibrant café culture, and lively arts scene.',
      'nearby.planica.title': 'Planica',
      'nearby.planica.description': 'World-famous ski jumping center and Nordic skiing venue in the heart of the Julian Alps.',
      
      // Seasonal Offers
      'offers.spring.title': 'Spring Package',
      'offers.spring.desc': '3 nights + kayaking on the lake. From €690.',
      'offers.summer.title': 'Summer Luxury',
      'offers.summer.desc': '5 nights, 2nd night free. Valid July–August.',
      'offers.autumn.title': 'Autumn Retreat',
      'offers.autumn.desc': '4 nights + wine tasting. From €890.',
      'offers.winter.title': 'Winter Wonderland',
      'offers.winter.desc': '3 nights + wellness package. From €750.',

      // Special Offers (detailed)
      'offers.earlyBird.title': 'Early Bird Discount',
      'offers.earlyBird.description': 'Book 60+ days in advance and receive 10% off your stay.',
      'offers.earlyBird.price': '10% off',
      'offers.earlyBird.tag': 'Recommended',
      'offers.romantic.title': 'Romantic Package',
      'offers.romantic.description': '3 nights + champagne + couples massage + sunset dinner.',
      'offers.romantic.price': 'From €890',
      'offers.romantic.tag': 'Romance',
      'offers.wellness.title': 'Wellness Retreat',
      'offers.wellness.description': '3 nights + daily yoga + 2 massages + healthy breakfast.',
      'offers.wellness.price': 'From €750',
      'offers.wellness.tag': 'Wellness',
      'offers.stay5.title': 'Stay 5, Pay 4',
      'offers.stay5.description': 'Book 5 nights in high season (Jul-Aug) and only pay for 4.',
      'offers.stay5.price': '1 night free',
      'offers.stay5.tag': 'Best Value',
      'offers.direct.title': 'Direct Booking Bonus',
      'offers.direct.description': 'Book directly through our website and receive a free room upgrade + welcome drink.',
      'offers.direct.price': 'Free upgrade',
      'offers.direct.tag': 'Exclusive',
      'offers.lastMinute.title': 'Last Minute Deal',
      'offers.lastMinute.description': 'Book within 7 days and get 15% off (subject to availability).',
      'offers.lastMinute.price': '15% off',
      'offers.lastMinute.tag': 'Hot Deal',
      
      // Common
      'common.book': 'Book',
      'common.learn': 'Learn More',
      'common.close': 'Close',
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.from': 'From',
      'common.perNight': 'per night',
      
      // Footer
      'footer.description': 'Luxury boutique hotel in the heart of Bled. A historic villa from 1878 transformed into a sanctuary of elegance.',
      'footer.contact': 'Contact',
      'footer.links': 'Quick Links',
      'footer.newsletter.title': 'Newsletter',
      'footer.newsletter.desc': 'Subscribe to our newsletter for exclusive offers.',
      'footer.newsletter.placeholder': 'Your email',
      'footer.newsletter.button': 'Subscribe',
      'footer.rights': 'All rights reserved.',

      // Why Choose Us
      'whyChoose.badge': 'Why Choose Us',
      'whyChoose.title': 'Why Villa Adora?',
      'whyChoose.subtitle': 'Discover what sets us apart and why guests from around the world keep coming back.',
      'whyChoose.bestPrice': 'Best Price Guarantee',
      'whyChoose.bestPriceDesc': 'We guarantee the best rate. If you find a lower price, we\'ll beat it by 10%.',
      'whyChoose.heritage': 'Historic Heritage',
      'whyChoose.heritageDesc': 'A villa from 1878, renovated with love for detail and respect for history.',
      'whyChoose.personalized': 'Personalized Service',
      'whyChoose.personalizedDesc': 'Every guest is special to us. We tailor your stay down to the smallest detail.',
      'whyChoose.awards': 'Award-Winning Quality',
      'whyChoose.awardsDesc': 'Recognized by guests and travel experts as one of the finest boutique hotels in Slovenia.',
      'whyChoose.concierge': '24/7 Concierge',
      'whyChoose.conciergeDesc': 'Our digital concierge Luka is available 24 hours a day, 7 days a week.',
      'whyChoose.location': 'Prime Location',
      'whyChoose.locationDesc': 'Directly on Lake Bled, with views of the island and castle. The best location in Bled.',
      'whyChoose.stat.rating': 'Average Rating',
      'whyChoose.stat.reviews': 'Guest Reviews',
      'whyChoose.stat.established': 'Established',
      'whyChoose.stat.returnGuests': 'Return Guests',

      // Seasonal Highlights
      'seasonal.badge': 'Seasonal Offers',
      'seasonal.title': 'This Season at Villa Adora',
      'seasonal.subtitle': 'Exclusive packages designed to make your stay unforgettable. Book directly for the best rates.',
      'seasonal.spring.title': 'Spring Awakening',
      'seasonal.spring.desc': '3 nights + kayaking on the lake + guided nature walk. Cherry blossoms and fresh Alpine air.',
      'seasonal.spring.badge': 'Spring',
      'seasonal.summer.title': 'Summer Luxury Escape',
      'seasonal.summer.desc': '5 nights with 2nd night free. Lake swimming, terrace dining, and sunset cruises.',
      'seasonal.summer.badge': 'Summer',
      'seasonal.wellness.title': 'Wellness Retreat',
      'seasonal.wellness.desc': '3 nights + daily yoga + 2 massages + healthy breakfast. Rejuvenate body and soul.',
      'seasonal.wellness.badge': 'Wellness',
      'seasonal.nights': 'nights',
      'seasonal.validUntil': 'Valid until',
      'seasonal.bookNow': 'Book Now',
      'seasonal.viewAllOffers': 'View All Offers',

      // Bled Seasons
      'seasons.title': 'Bled Through the Seasons',
      'seasons.subtitle': 'Every season brings its own magic',
      'seasons.spring.title': 'Spring',
      'seasons.spring.desc': 'Cherry blossoms, warm sunny days, and a tranquil lake. Perfect for kayaking and hiking.',
      'seasons.summer.title': 'Summer',
      'seasons.summer.desc': 'Warm water for swimming, vibrant terraces, and long evenings. Blooming flowers and local delicacies.',
      'seasons.autumn.title': 'Autumn',
      'seasons.autumn.desc': 'Golden foliage, fine wines, and mystical foggy mornings. Ideal for a romantic retreat.',
      'seasons.winter.title': 'Winter',
      'seasons.winter.desc': 'Blanketed in snow, Bled becomes a fairytale. Christmas market, skiing, and warm drinks.',

      // Culinary & Dining
      'culinary.subtitle': 'Culinary Experiences',
      'culinary.title': 'Flavors of Bled',
      'culinary.description': 'Discover the richness of local flavors offered at our hotel. From traditional cream cake to premium Slovenian wines.',
      'culinary.breakfast.title': 'Lakeside Breakfast',
      'culinary.breakfast.description': 'Start your day with a lavish buffet breakfast on the terrace overlooking the lake. Fresh pastries, local cheeses, homemade jams, and seasonal fruits.',
      'culinary.restaurant.title': 'Restaurant 1878',
      'culinary.restaurant.description': 'Our restaurant offers a modern interpretation of Slovenian cuisine with local ingredients. Degustation menus with wine pairings.',
      'culinary.terrace.title': 'Lakeside Terrace',
      'culinary.terrace.description': 'Enjoy coffee or dinner on our exclusive terrace right on the lake. An unforgettable experience at sunset.',
      'culinary.experiences.title': 'Cooking Workshops',
      'culinary.experiences.description': 'Join our cooking workshops — learn to make cream cake, traditional potica, or taste the finest Slovenian wines.',
      'culinary.cta': 'Book a Table',

      // Newsletter
      'newsletter.title': 'Stay Connected',
      'newsletter.description': 'Subscribe to our newsletter and receive exclusive offers, seasonal packages, and news from Villa Adora.',
      'newsletter.placeholder': 'Your email address',
      'newsletter.button': 'Subscribe',
      'newsletter.success': 'Thank you for subscribing! You will receive a confirmation email.',
      'newsletter.error': 'Please enter a valid email address.',
      'newsletter.privacy': 'Your email will be used exclusively for our newsletters. You can unsubscribe at any time.',

      // FAQ
      'faq.checkin.question': 'What are the check-in and check-out times?',
      'faq.checkin.answer': 'Check-in is from 15:00 to 22:00. Check-out is by 11:00. Late check-in and late check-out are available on request — please let us know in advance.',
      'faq.cancellation.question': 'What is the cancellation policy?',
      'faq.cancellation.answer': 'Free cancellation up to 48 hours before arrival. Cancellations within 48 hours before arrival are charged for the first night. For high season bookings (July-August), cancellation must be made 72 hours in advance.',
      'faq.parking.question': 'Is free parking available?',
      'faq.parking.answer': 'Yes, free private parking is available on-site for all guests. The parking area is secured and under surveillance.',
      'faq.pets.question': 'Are pets allowed?',
      'faq.pets.answer': 'Yes, pets are allowed on request. Please let us know in advance. An additional cleaning fee of €30 per stay applies.',
      'faq.breakfast.question': 'Is breakfast included in the rate?',
      'faq.breakfast.answer': 'Yes, a lavish buffet breakfast is included in the room rate. Breakfast is served from 7:30 to 10:30 on the terrace overlooking the lake. Vegan and gluten-free options are available.',
      'faq.airport.question': 'How do I get from the airport to Villa Adora?',
      'faq.airport.answer': 'Ljubljana Jože Pučnik Airport is 35 km away (approximately 30 minutes by car). We offer airport transfer on request (€40 one way). Klagenfurt Airport (Austria) is also 70 km away.',
      'faq.wifi.question': 'Is free WiFi available?',
      'faq.wifi.answer': 'Yes, free high-speed WiFi is available throughout the hotel and in all suites. The connection is reliable even on the terrace and in the garden area.',
      'faq.spa.question': 'Do you have a wellness center?',
      'faq.spa.answer': 'Yes, our wellness center includes a Finnish sauna, Turkish bath, and massage services. Wellness facilities are free for all guests. Massages must be booked in advance.',
      'faq.transport.question': 'Do you offer transport or bicycle rental?',
      'faq.transport.answer': 'Yes, we offer complimentary mountain bike rental for all guests. We also provide electric vehicle transport around Bled and the surrounding area. For longer excursions (Vintgar, Triglav National Park), we organize transport on request.',
      'faq.miniBar.question': 'Does the suite have a mini bar?',
      'faq.miniBar.answer': 'Yes, all suites have a mini bar with selected Slovenian wines, beverages, and snacks. It also includes coffee, tea, and hot chocolate for self-service.',

      // Virtual Tour
      'virtualTour.lobby.title': 'Lobby & Reception',
      'virtualTour.lobby.description': 'Experience the grand entrance of Villa Adora with its historic charm and elegant reception area.',
      'virtualTour.suite.title': 'Luxury Suite Walkthrough',
      'virtualTour.suite.description': 'Step inside our signature suites and explore every detail of the luxurious interiors.',
      'virtualTour.lake.title': 'Lake View Terrace',
      'virtualTour.lake.description': 'Enjoy the breathtaking panoramic views of Lake Bled from our exclusive terrace.',
      'virtualTour.dining.title': 'Restaurant & Dining',
      'virtualTour.dining.description': 'Discover our elegant restaurant and lakeside dining experience.',

      // Book Direct Benefits
      'bookDirect.badge': 'Book Direct & Save',
      'bookDirect.title': 'Why Book Direct With Us?',
      'bookDirect.subtitle': 'Skip the middleman and get the best value when you book directly through our website.',
      'bookDirect.bestPrice.title': 'Best Price Guaranteed',
      'bookDirect.bestPrice.description': 'If you find a lower price elsewhere, we will match it. Plus get an additional 5% discount for booking direct.',
      'bookDirect.freeBreakfast.title': 'Complimentary Breakfast',
      'bookDirect.freeBreakfast.description': 'Enjoy a full gourmet breakfast with lake views — included free when you book direct (€25 value per person).',
      'bookDirect.freeWifi.title': 'Premium WiFi',
      'bookDirect.freeWifi.description': 'High-speed fiber internet throughout the property, perfect for remote work or streaming.',
      'bookDirect.upgrade.title': 'Free Room Upgrade',
      'bookDirect.upgrade.description': 'Subject to availability, direct bookings receive priority for complimentary room upgrades.',
      'bookDirect.directSupport.title': 'Direct Support',
      'bookDirect.directSupport.description': 'Speak directly with our team for personalized service, special requests, and local recommendations.',
      'bookDirect.flexible.title': 'Flexible Cancellation',
      'bookDirect.flexible.description': 'Free cancellation up to 48 hours before arrival — more flexible than third-party booking sites.',
      'bookDirect.cta': 'Check Availability',

      // Trust Badges
      'trust.secureBooking': 'Secure Booking',
      'trust.noPrepayment': 'No Prepayment',
      'trust.ssl': 'SSL Encrypted',
      'trust.bestPrice': 'Best Price',

      // Wellness Preview
      'wellness.sauna.title': 'Finnish Sauna',
      'wellness.sauna.desc': 'Warm sauna with wood aromas and lake views. Prepare for complete relaxation in our exclusive Finnish sauna.',
      'wellness.turkish.title': 'Turkish Bath',
      'wellness.turkish.desc': 'Traditional Turkish bath for complete relaxation. Warm steam and skin purification in the comfort of a gallery with lake views.',
      'wellness.massage.title': 'Massages',
      'wellness.massage.desc': 'Professional massages by a therapist — aromatherapy, sports, and relaxation. Each massage is tailored to your needs.',
      'wellness.relaxation.title': 'Relaxation Zone',
      'wellness.relaxation.desc': 'A peaceful zone for reading, meditation, and relaxation with lake views. Relaxation wraps and sound therapy are also available.',
      'wellness.infinity.title': 'Infinity Pool',
      'wellness.infinity.desc': 'Outdoor pool with lake views and a star-deck. Warm water throughout the year.',
    },
    de: {
      // Navigation
      'nav.home': 'Startseite',
      'nav.about': 'Über uns',
      'nav.suites': 'Suiten',
      'nav.activities': 'Aktivitäten',
      'nav.gallery': 'Galerie',
      'nav.contact': 'Kontakt',
      'nav.reservation': 'Reservierung',
      'nav.giftVoucher': 'Geschenkgutschein',
      'nav.wellness': 'Wellness',
      'nav.admin': 'Admin',

      // Gift Voucher
      'giftVoucher.title': 'Geschenkgutschein',
      'giftVoucher.subtitle': 'Verschenken Sie ein unvergessliches Erlebnis am Bleder See',
      'giftVoucher.howItWorks': 'So funktioniert es',
      'giftVoucher.step1': 'Betrag und Motto wählen',
      'giftVoucher.step2': 'Empfängerdaten eingeben',
      'giftVoucher.step3': 'Sie erhalten eine Bestätigung, der Gutschein wird dem Empfänger zugestellt',
      'giftVoucher.step4': 'Der Empfänger löst den Gutschein für seinen Aufenthalt ein',
      'giftVoucher.validity': 'Geschenkgutscheine sind 12 Monate ab Kaufdatum gültig.',

      // Hero
      'hero.title': 'Villa Adora',
      'hero.subtitle': 'Luxushotel am Bleder See',
      'hero.description': 'Erleben Sie unvergesslichen Luxus in unserer historischen Villa am Ufer des Bleder Sees.',
      'hero.book': 'Jetzt buchen',
      'hero.learn': 'Mehr erfahren',

      // About
      'about.title': 'Über uns',
      'about.subtitle': 'Villa Adora',
      'about.description': 'Villa Adora ist eine denkmalgeschichtliche Villa aus dem Jahr 1878, die liebevoll in ein Boutique-Luxus-Hotel umgewandelt wurde. Direkt am Ufer des Bleder Sees gelegen.',

      // Suites
      'suites.title': 'Unsere Luxus-Suiten',
      'suites.princess.title': 'Prinzessin-Suite',
      'suites.princess.description': 'Sehr schön eingerichtete und geschmackvoll dekorierte Suite (55 m²) mit Wohnbereich, Schlafzimmer und Badezimmer. Der kleine Turm bietet Blick auf den wunderschönen Bleder See.',
      'suites.luxury.title': 'Luxus-Suite',
      'suites.luxury.description': 'Für ultimativen Komfort und Eleganz mit unvergesslichem Seeblick konzipiert.',
      'suites.penthouse.title': 'Penthouse-Suite',
      'suites.penthouse.description': 'Der einzigartigste Raum in unserem Haus, geschmackvoll gestaltet auf zwei Etagen (60 m²). Gemütliche Atmosphäre mit atemberaubendem Ausblick.',
      'suites.swan.title': 'Schwanen-Suite',
      'suites.swan.description': 'Eine elegante und geräumige Suite, die den perfekten Rückzugsort für Ihren Aufenthalt bietet.',
      'suites.island.title': 'Insel-Suite',
      'suites.island.description': 'Eine stilvolle Luxus-Suite (65 m²) im ersten Stock. Bietet atemberaubenden Blick auf den See und die Bleder Insel. Mit zwei Schlafzimmern und zwei Balkonen.',
      'suites.prestige.title': 'Prestige-Suite',
      'suites.prestige.description': 'Absolute Harmonie aus kunstvoller Dekoration und Großzügigkeit (72 m²). Im Erdgeschoß gelegen mit Seeblick aus jedem Fenster.',

      // Activities
      'activities.title': 'Aktivitäten & Erlebnisse',
      'activities.lake.title': 'See-Aktivitäten',
      'activities.lake.description': 'Abenteuer am Bleder See: Bootsfahrt zur Insel, Kajak, Stand-Up-Paddeln, Angeln und Picknick am See.',
      'activities.mountain.title': 'Bergwandern',
      'activities.mountain.description': 'Erkunden Sie die herrlichen Bergwege rund um Bled. Besuchen Sie Ojstrica, Berghütten und genießen Sie spektakuläre Panoramablicke.',
      'activities.culinary.title': 'Kulinarische Erlebnisse',
      'activities.culinary.description': 'Kosten Sie lokale Spezialitäten in unserem Hotel oder besuchen Sie traditionelle Restaurants. Genießen Sie Kremeschnitte und lokale Weine.',
      'activities.spa.title': 'Spa & Entspannung',
      'activities.spa.description': 'Entspannen Sie in unserem Luxus-Wellnesscenter mit Massagen, Sauna und Seeblick.',
      'activities.culture.title': 'Kulturelles Erbe',
      'activities.culture.description': 'Besuchen Sie die Bleder Burg, die Inselkirche, die Vintgar-Schlucht und zahlreiche Museen.',
      'activities.romantic.title': 'Romantische Erlebnisse',
      'activities.romantic.description': 'Sonnenuntergang-Dinner, Bootsfahrt zur Insel, Paarmassage und Kremeschnitte mit Klaviermusik.',
      'activities.winter.title': 'Winteraktivitäten',
      'activities.winter.description': 'Skifahren in Krvavec und Voklo, Skispringen in Planica, Schlittenfahren, Schlittschuhlaufen auf dem See.',
      'activities.adventure.title': 'Abenteuer-Erlebnisse',
      'activities.adventure.canyoning': 'Canyoning in Bohinj, Rafting auf der Soča, Zipline über Vintgar und Mountainbiking im Triglav-Nationalpark.',

      // Gallery
      'gallery.title': 'Fotogalerie',
      'gallery.subtitle': 'Die Seele der Villa Adora einfangen',
      'gallery.followUs': 'Folgen Sie unserer Geschichte auf Instagram',
      'gallery.followDesc': 'Für die besten Fotos und Momente aus Villa Adora',
      'gallery.filter.all': 'Alle',
      'gallery.filter.exterior': 'Außenbereich',
      'gallery.filter.suites': 'Suiten',
      'gallery.filter.lake': 'See',
      'gallery.filter.dining': 'Gastronomie',

      // Contact
      'contact.title': 'Standort & Kontakt',
      'contact.address': 'Cesta svobode 35, 4260 Bled, Slowenien',
      'contact.phone': '+386 51 603 858',
      'contact.email': 'evita.vilebled@gmail.com',
      'contact.hours': '7:00 - 22:00',

      // Reservation
      'reservation.title': 'Reservierung',
      'reservation.firstName': 'Vorname',
      'reservation.lastName': 'Nachname',
      'reservation.email': 'E-Mail',
      'reservation.phone': 'Telefon',
      'reservation.checkIn': 'Anreisedatum',
      'reservation.checkOut': 'Abreisedatum',
      'reservation.adults': 'Anzahl Erwachsene',
      'reservation.roomType': 'Zimmertyp',
      'reservation.requests': 'Sonderwünsche',
      'reservation.submit': 'Reservierung absenden',

      // Nearby
      'nearby.island.title': 'Bleder Insel',
      'nearby.island.description': 'Sloweniens ikonische Insel mit malerischer Kirche, erreichbar mit traditionellem Holzboot "Pletna".',
      'nearby.castle.title': 'Bleder Burg',
      'nearby.castle.description': 'Mittelalterliche Burg auf einer Klippe mit Panoramablick auf den See und die umliegenden Alpen.',
      'nearby.vintgar.title': 'Vintgar-Schlucht',
      'nearby.vintgar.description': 'Atemberaubende 1,6 km lange Schlucht mit Stege, Wasserfällen und historischer Eisenbahnbrücke.',
      'nearby.triglav.title': 'Triglav-Nationalpark',
      'nearby.triglav.description': 'Einer der ältesten Nationalparks Europas. Heimat des Triglav, Sloweniens höchstem Berg.',
      'nearby.ljubljana.title': 'Ljubljana',
      'nearby.ljubljana.description': 'Liebenswerte Hauptstadt Sloweniens mit barocker Architektur und lebhafter Kulturszene.',
      'nearby.planica.title': 'Planica',
      'nearby.planica.description': 'Weltbekanntes Skisprungzentrum und Nordische Skistätte im Herzen der Julischen Alpen.',

      // Seasonal Offers
      'offers.spring.title': 'Frühlingspaket',
      'offers.spring.desc': '3 Nächte + Kajak auf dem See. Ab €690.',
      'offers.summer.title': 'Sommer-Luxus',
      'offers.summer.desc': '5 Nächte, 2. Nacht kostenlos. Gültig Juli–August.',
      'offers.autumn.title': 'Herbst-Urlaub',
      'offers.autumn.desc': '4 Nächte + Weinverkostung. Ab €890.',
      'offers.winter.title': 'Winterwunder',
      'offers.winter.desc': '3 Nächte + Wellness-Paket. Ab €750.',

      // Special Offers
      'offers.earlyBird.title': 'Frühbucher-Rabatt',
      'offers.earlyBird.description': 'Buchen Sie 60+ Tage im Voraus und erhalten 10% Rabatt.',
      'offers.earlyBird.price': '10% Rabatt',
      'offers.earlyBird.tag': 'Empfohlen',
      'offers.romantic.title': 'Romantisches Paket',
      'offers.romantic.description': '3 Nächte + Sekt + Paarmassage + Sonnenuntergang-Dinner.',
      'offers.romantic.price': 'Ab €890',
      'offers.romantic.tag': 'Romantik',
      'offers.wellness.title': 'Wellness-Retreat',
      'offers.wellness.description': '3 Nächte + tägliches Yoga + 2 Massagen + gesundes Frühstück.',
      'offers.wellness.price': 'Ab €750',
      'offers.wellness.tag': 'Wellness',
      'offers.stay5.title': '5 Nächte, 4 bezahlen',
      'offers.stay5.description': 'Buchen Sie 5 Nächte in der Hochsaison (Juli-Aug) und zahlen Sie nur 4.',
      'offers.stay5.price': '1 Nacht kostenlos',
      'offers.stay5.tag': 'Bestes Angebot',
      'offers.direct.title': 'Direktbuchungs-Bonus',
      'offers.direct.description': 'Buchen Sie direkt über unsere Website und erhalten ein kostenloses Room-Upgrade + Willkommensgetränk.',
      'offers.direct.price': 'Kostenloses Upgrade',
      'offers.direct.tag': 'Exklusiv',
      'offers.lastMinute.title': 'Last-Minute-Angebot',
      'offers.lastMinute.description': 'Buchen Sie innerhalb von 7 Tagen und erhalten 15% Rabatt (vorbehaltlich Verfügbarkeit).',
      'offers.lastMinute.price': '15% Rabatt',
      'offers.lastMinute.tag': 'Hot Deal',

      // Common
      'common.book': 'Buchen',
      'common.learn': 'Mehr erfahren',
      'common.close': 'Schließen',
      'common.loading': 'Laden...',
      'common.error': 'Fehler',
      'common.success': 'Erfolg',
      'common.from': 'Ab',
      'common.perNight': 'pro Nacht',

      // Footer
      'footer.description': 'Luxushotel im Herzen von Bled. Eine historische Villa aus dem Jahr 1878, verwandelt in ein Refugium der Eleganz.',
      'footer.contact': 'Kontakt',
      'footer.links': 'Links',
      'footer.newsletter.title': 'Newsletter',
      'footer.newsletter.desc': 'Abonnieren Sie unseren Newsletter für exklusive Angebote.',
      'footer.newsletter.placeholder': 'Ihre E-Mail',
      'footer.newsletter.button': 'Abonnieren',
      'footer.rights': 'Alle Rechte vorbehalten.',

      // Why Choose Us
      'whyChoose.badge': 'Warum uns wählen',
      'whyChoose.title': 'Warum Villa Adora?',
      'whyChoose.subtitle': 'Entdecken Sie, was uns ausmacht und warum Gäste aus der ganzen Welt wiederkommen.',
      'whyChoose.bestPrice': 'Bestpreis-Garantie',
      'whyChoose.bestPriceDesc': 'Wir garantieren den besten Preis. Wenn Sie einen niedrigeren Preis finden, unterbieten wir ihn um 10%.',
      'whyChoose.heritage': 'Historisches Erbe',
      'whyChoose.heritageDesc': 'Eine Villa aus dem Jahr 1878, mit Liebe zum Detail und Respekt vor der Geschichte renoviert.',
      'whyChoose.personalized': 'Persönlicher Service',
      'whyChoose.personalizedDesc': 'Jeder Gast ist für uns besonders. Wir gestalten Ihren Aufenthalt bis ins kleinste Detail.',
      'whyChoose.awards': 'Ausgezeichnete Qualität',
      'whyChoose.awardsDesc': 'Von Gästen und Reisespezialisten als eines der besten Boutique-Hotels Sloweniens anerkannt.',
      'whyChoose.concierge': '24/7 Concierge',
      'whyChoose.conciergeDesc': 'Unser digitaler Concierge Luka ist 24 Stunden am Tag, 7 Tage die Woche verfügbar.',
      'whyChoose.location': 'Erstklassige Lage',
      'whyChoose.locationDesc': 'Direkt am Bleder See, mit Blick auf die Insel und die Burg. Die beste Lage in Bled.',
      'whyChoose.stat.rating': 'Durchschnittsbewertung',
      'whyChoose.stat.reviews': 'Gästebewertungen',
      'whyChoose.stat.established': 'Gegründet',
      'whyChoose.stat.returnGuests': 'Wiederkommende Gäste',

      // Seasons
      'seasons.title': 'Bled durch die Jahreszeiten',
      'seasons.subtitle': 'Jede Jahreszeit bringt ihre eigene Magie',
      'seasons.spring.title': 'Frühling',
      'seasons.spring.desc': 'Kirschblüte, warme Sonnentage und ein ruhiger See. Perfekt für Kajak und Wandern.',
      'seasons.summer.title': 'Sommer',
      'seasons.summer.desc': 'Warmes Wasser zum Schwimmen, lebendige Terrassen und lange Abende.',
      'seasons.autumn.title': 'Herbst',
      'seasons.autumn.desc': 'Goldenes Laub, feine Weine und mystische Morgennebel.',
      'seasons.winter.title': 'Winter',
      'seasons.winter.desc': 'Eingehüllt in Schnee wird Bled zu einem Märchen. Weihnachtsmarkt, Skifahren und warme Getränke.',

      // Culinary
      'culinary.subtitle': 'Kulinarische Erlebnisse',
      'culinary.title': 'Geschmäcker von Bled',
      'culinary.description': 'Entdecken Sie die Vielfalt lokaler Geschmäcker in unserem Hotel. Von traditioneller Kremeschnitte bis hin zu erstklassigen slowenischen Weinen.',
      'culinary.breakfast.title': 'Frühstück am See',
      'culinary.breakfast.description': 'Starten Sie den Day mit einem reichhaltigen Frühstücksbuffet auf der Terrasse mit Seeblick.',
      'culinary.restaurant.title': 'Restaurant 1878',
      'culinary.restaurant.description': 'Unser Restaurant bietet eine moderne Interpretation slowenischer Küche mit lokalen Zutaten.',
      'culinary.terrace.title': 'Seeterrasse',
      'culinary.terrace.description': 'Genießen Sie Kaffee oder Dinner auf unserer exklusivien Terrasse direkt am See.',
      'culinary.experiences.title': 'Kochworkshops',
      'culinary.experiences.description': 'Nehmen Sie an unseren Kochworkshops teil — lernen Sie Kremeschnitte, traditionelle Potica oder die besten slowenischen Weine zuzubereiten.',
      'culinary.cta': 'Tisch reservieren',

      // Newsletter
      'newsletter.title': 'In Kontakt bleiben',
      'newsletter.description': 'Abonnieren Sie unseren Newsletter und erhalten Sie exklusive Angebote, Saisonpakete und Neuigkeiten von Villa Adora.',
      'newsletter.placeholder': 'Ihre E-Mail-Adresse',
      'newsletter.button': 'Abonnieren',
      'newsletter.success': 'Vielen Dank für Ihr Abonnement!',
      'newsletter.error': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
      'newsletter.privacy': 'Ihre E-Mail wird ausschließlich für unseren Newsletter verwendet.',

      // FAQ
      'faq.checkin.question': 'Was sind die Check-in- und Check-out-Zeiten?',
      'faq.checkin.answer': 'Check-in ist von 15:00 bis 22:00. Check-out ist bis 11:00. Spätere Zeiten sind auf Anfrage möglich.',
      'faq.cancellation.question': 'Wie ist die Stornierungsrichtlinie?',
      'faq.cancellation.answer': 'Kostenlose Stornierung bis 48 Stunden vor Anreise. Bei Hochsaison (Juli-August) gilt eine Frist von 72 Stunden.',
      'faq.parking.question': 'Ist kostenloser Parkplatz verfügbar?',
      'faq.parking.answer': 'Ja, kostenlose private Parkplätze stehen allen Gästen zur Verfügung.',
      'faq.pets.question': 'Sind Haustiere erlaubt?',
      'faq.pets.answer': 'Ja, Haustiere sind auf Anfrage erlaubt. Eine zusätzliche Reinigungsgebühr von €30 pro Aufenthalt gilt.',
      'faq.breakfast.question': 'Ist Frühstück im Preis enthalten?',
      'faq.breakfast.answer': 'Ja, ein reichhaltiges Frühstücksbuffet ist im Zimmerpreis enthalten. Von 7:30 bis 10:30 auf der Terrasse mit Seeblick serviert.',
      'faq.airport.question': 'Wie komme ich vom Flughafen zur Villa Adora?',
      'faq.airport.answer': 'Der Flughafen Ljubljana Jože Pučnik ist 35 km entfernt. Wir bieten Transfers auf Anfrage (€40 einfach).',
      'faq.wifi.question': 'Ist kostenloses WLAN verfügbar?',
      'faq.wifi.answer': 'Ja, kostenloses Highspeed-WLAN ist im gesamten Hotel und allen Suiten verfügbar.',
      'faq.spa.question': 'Haben Sie ein Wellnesscenter?',
      'faq.spa.answer': 'Ja, unser Wellnesscenter umfasst finnische Sauna, türkisches Bad und Massagen. Die Nutzung ist für alle Gäste kostenlos.',
      'faq.transport.question': 'Bieten Sie Transport oder Fahrradverleih an?',
      'faq.transport.answer': 'Ja, wir bieten kostenlose Mountainbike-Vermietung für alle Gäste.',
      'faq.miniBar.question': 'Hat die Suite eine Minibar?',
      'faq.miniBar.answer': 'Ja, alle Suiten haben eine Minibar mit ausgewählten slowenischen Weinen, Getränken und Snacks.',

      // Virtual Tour
      'virtualTour.lobby.title': 'Lobby & Rezeption',
      'virtualTour.lobby.description': 'Erleben Sie den grandiosen Eingang der Villa Adora mit historischem Charme.',
      'virtualTour.suite.title': 'Luxus-Suite-Rundgang',
      'virtualTour.suite.description': 'Treten Sie ein in unsere Signature-Suiten und erkunden Sie jedes Detail.',
      'virtualTour.lake.title': 'Seeblick-Terrasse',
      'virtualTour.lake.description': 'Genießen Sie den atemberaubenden Panoramablick auf den Bleder See.',
      'virtualTour.dining.title': 'Restaurant & Gastronomie',
      'virtualTour.dining.description': 'Entdecken Sie unser elegantes Restaurant und das kulinarische Erlebnis am See.',

      // Book Direct
      'bookDirect.badge': 'Direkt buchen & sparen',
      'bookDirect.title': 'Warum direkt bei uns buchen?',
      'bookDirect.subtitle': 'Überspringen Sie den Zwischenhändler und erhalten Sie den besten Wert.',
      'bookDirect.bestPrice.title': 'Bestpreis garantiert',
      'bookDirect.bestPrice.description': 'Wenn Sie einen niedrigeren Preis finden, passen wir uns an. Plus 5% Rabatt für Direktbuchung.',
      'bookDirect.freeBreakfast.title': 'Kostenloses Frühstück',
      'bookDirect.freeBreakfast.description': 'Genießen Sie ein reichhaltiges Gourmet-Frühstück mit Seeblick — kostenlos bei Direktbuchung.',
      'bookDirect.freeWifi.title': 'Premium WLAN',
      'bookDirect.freeWifi.description': 'Highspeed-Internet im gesamten Hotel.',
      'bookDirect.upgrade.title': 'Kostenloses Room-Upgrade',
      'bookDirect.upgrade.description': 'Direktbuchungen erhalten Priorität für kostenlose Zimmer-Upgrades.',
      'bookDirect.directSupport.title': 'Direkter Support',
      'bookDirect.directSupport.description': 'Sprechen Sie direkt mit unserem Team für persönlichen Service.',
      'bookDirect.flexible.title': 'Flexible Stornierung',
      'bookDirect.flexible.description': 'Kostenlose Stornierung bis 48 Stunden vor Anreise.',
      'bookDirect.cta': 'Verfügbarkeit prüfen',

      // Trust Badges
      'trust.secureBooking': 'Sichere Buchung',
      'trust.noPrepayment': 'Keine Vorauszahlung',
      'trust.ssl': 'SSL-verschlüsselt',
      'trust.bestPrice': 'Bester Preis',

      // Wellness Preview
      'wellness.sauna.title': 'Finnisch Sauna',
      'wellness.sauna.desc': 'Warme Sauna mit Holzaromen und Seeblick. Bereiten Sie sich auf vollständige Entspannung vor.',
      'wellness.turkish.title': 'Schwimmbad',
      'wellness.turkish.desc': 'Traditionelles türkisches Bad. Warme Dampf und Hautreinigung mit Blick auf den See.',
      'wellness.massage.title': 'Massage',
      'wellness.massage.desc': 'Professionelle Massagen durch einen Therapeuten. Aromatherapie, Sport- und Entspannungsmassagen.',
      'wellness.relaxation.title': 'Entspannungszone',
      'wellness.relaxation.desc': 'Ein ruhiger Ort für Lesen, Meditation und Entspannung mit Blick auf den See.',
      'wellness.infinity.title': 'Infinity-Pool',
      'wellness.infinity.desc': 'Außenpool mit Seeblick und Sonnendeck. Warmes Wasser das ganze Jahr.',
    },
    it: {
      // Navigation
      'nav.home': 'Home',
      'nav.about': 'Chi siamo',
      'nav.suites': 'Suite',
      'nav.activities': 'Attività',
      'nav.gallery': 'Galleria',
      'nav.contact': 'Contatti',
      'nav.reservation': 'Prenotazione',
      'nav.giftVoucher': 'Buono regalo',
      'nav.wellness': 'Wellness',
      'nav.admin': 'Admin',

      // Gift Voucher
      'giftVoucher.title': 'Buono regalo',
      'giftVoucher.subtitle': 'Regala un\'esperienza indimenticabile sul lago di Bled',
      'giftVoucher.howItWorks': 'Come funziona',
      'giftVoucher.step1': 'Scegli l\'importo e il tema',
      'giftVoucher.step2': 'Inserisci i dati del destinatario',
      'giftVoucher.step3': 'Ricevi una conferma, il buono viene consegnato al destinatario',
      'giftVoucher.step4': 'Il destinatario utilizza il buono per il soggiorno',
      'giftVoucher.validity': 'I buoni regalo sono validi per 12 mesi dall\'acquisto.',

      // Hero
      'hero.title': 'Villa Adora',
      'hero.subtitle': 'Hotel di lusso sul lago di Bled',
      'hero.description': 'Vivi un\'esperienza indimenticabile nella nostra villa storica sulle rive del lago di Bled.',
      'hero.book': 'Prenota ora',
      'hero.learn': 'Scopri di più',

      // About
      'about.title': 'Chi siamo',
      'about.subtitle': 'Villa Adora',
      'about.description': 'Villa Adora è una villa storica protetta costruita nel 1878, accuratamente ristrutturata in un hotel boutique di lusso. Situata direttamente sulla riva del lago di Bled.',

      // Suites
      'suites.title': 'Le nostre suite di lusso',
      'suites.princess.title': 'Suite Principessa',
      'suites.princess.description': 'Suite molto ben arredata e decorata con gusto (55 m²) con zona giorno, camera da letto e bagno. La piccola torre si affaccia sul bellissimo lago di Bled.',
      'suites.luxury.title': 'Suite Luxury',
      'suites.luxury.description': 'Progettata per il massimo comfort e eleganza con viste indimenticabili sul lago.',
      'suites.penthouse.title': 'Suite Penthouse',
      'suites.penthouse.description': 'Lo spazio più unico della nostra casa, disposto su due piani (60 m²). Atmosfera accogliente con viste mozzafiato.',
      'suites.swan.title': 'Suite Cigno',
      'suites.swan.description': 'Una suite elegante e spaziosa che offre il rifugio perfetto per il vostro soggiorno.',
      'suites.island.title': 'Suite Isola',
      'suites.island.description': 'Una suite di lusso elegante (55 m²) al primo piano. Offre viste mozzafiato sul lago e sull\'Isola di Bled. Con due camere da letto e due balconi.',
      'suites.prestige.title': 'Suite Prestige',
      'suites.prestige.description': 'Assoluta armonia tra decorazione artistica e spaziosità (72 m²). Situata al piano terra con viste sul lago da ogni finestra.',

      // Activities
      'activities.title': 'Attività ed esperienze',
      'activities.lake.title': 'Attività sul lago',
      'activities.lake.description': 'Avventure sul lago di Bled: gita in barca all\'isola, kayak, stand-up paddle, pesca e picnic sul lago.',
      'activities.mountain.title': 'Escursioni in montagna',
      'activities.mountain.description': 'Esplorate i magnifici sentieri montani intorno a Bled. Visitate Ojstrica, i rifugi e godetevi viste panoramiche spettacolari.',
      'activities.culinary.title': 'Esperienze culinarie',
      'activities.culinary.description': 'Assaggiate le specialità locali nel nostro hotel o visitate i ristoranti tradizionali. Godetevi la crema di Bled e i vini locali.',
      'activities.spa.title': 'Spa e relax',
      'activities.spa.description': 'Rilassatevi nel nostro centro wellness di lusso con massaggi, sauna e viste sul lago.',
      'activities.culture.title': 'Patrimonio culturale',
      'activities.culture.description': 'Visitate il Castello di Bled, la chiesa sull\'isola, la Gola di Vintgar e numerosi musei.',
      'activities.romantic.title': 'Esperienze romantiche',
      'activities.romantic.description': 'Cena al tramonto, gita in barca all\'isola, massaggio per coppia e crema di Bled con musica di pianoforte.',
      'activities.winter.title': 'Attività invernali',
      'activities.winter.description': 'Sci a Krvavec e Voklo, salto con gli sci a Planica, slittino, pattinaggio sul lago.',
      'activities.adventure.title': 'Esperienze avventurose',
      'activities.adventure.description': 'Canyoning a Bohinn, rafting sul fiume Soča, zipline sopra Vintgar e mountain biking nel Parco Nazionale del Triglav.',

      // Gallery
      'gallery.title': 'Galleria fotografica',
      'gallery.subtitle': 'Catturare l\'anima di Villa Adora',
      'gallery.followUs': 'Segui la nostra storia su Instagram',
      'gallery.followDesc': 'Per le migliori foto e momenti di Villa Adora',
      'gallery.filter.all': 'Tutti',
      'gallery.filter.exterior': 'Esterno',
      'gallery.filter.suites': 'Suite',
      'gallery.filter.lake': 'Lago',
      'gallery.filter.dining': 'Ristorazione',

      // Contact
      'contact.title': 'Posizione e contatti',
      'contact.address': 'Cesta svobode 35, 4260 Bled, Slovenia',
      'contact.phone': '+386 51 603 858',
      'contact.email': 'evita.vilebled@gmail.com',
      'contact.hours': '7:00 - 22:00',

      // Reservation
      'reservation.title': 'Prenotazione',
      'reservation.firstName': 'Nome',
      'reservation.lastName': 'Cognome',
      'reservation.email': 'Email',
      'reservation.phone': 'Telefono',
      'reservation.checkIn': 'Data di arrivo',
      'reservation.checkOut': 'Data di partenza',
      'reservation.adults': 'Numero di adulti',
      'reservation.roomType': 'Tipo di camera',
      'reservation.requests': 'Richieste speciali',
      'reservation.submit': 'Invia prenotazione',

      // Nearby
      'nearby.island.title': 'Isola di Bled',
      'nearby.island.description': 'L\'icona della Slovenia — una piccola isola con una chiesa pittoresca, raggiungibile con la tradizionale barca di legno "pletna".',
      'nearby.castle.title': 'Castello di Bled',
      'nearby.castle.description': 'Castello medievale su una rupe con viste panoramiche sul lago e sulle Alpi circostanti.',
      'nearby.vintgar.title': 'Gola di Vintgar',
      'nearby.vintgar.description': 'Stupenda gola di 1,6 km con passerelle, cascate e un ponte ferroviario storico.',
      'nearby.triglav.title': 'Parco Nazionale del Triglav',
      'nearby.triglav.description': 'Uno dei parchi nazionali più antichi d\'Europa. Casa del Monte Triglav, la vetta più alta della Slovenia.',
      'nearby.ljubljana.title': 'Lubiana',
      'nearby.ljubljana.description': 'Affascinante capitale della Slovenia con architettura baroca e una vivace scena culturale.',
      'nearby.planica.title': 'Planica',
      'nearby.planica.description': 'Centro mondiale di salto con gli sci e di sci nordico nel cuore delle Alpi Giulie.',

      // Seasonal Offers
      'offers.spring.title': 'Pacchetto primavera',
      'offers.spring.desc': '3 notti + kayak sul lago. Da €690.',
      'offers.summer.title': 'Lusso estivo',
      'offers.summer.desc': '5 notti, 2° notte gratis. Valido luglio–agosto.',
      'offers.autumn.title': 'Ritiro autunnale',
      'offers.autumn.desc': '4 notti + degustazione di vini. Da €890.',
      'offers.winter.title': 'Meraviglia invernale',
      'offers.winter.desc': '3 notti + pacchetto wellness. Da €750.',

      // Special Offers
      'offers.earlyBird.title': 'Sconto Early Bird',
      'offers.earlyBird.description': 'Prenota con 60+ giorni di anticipo e ricevi il 10% di sconto.',
      'offers.earlyBird.price': '10% di sconto',
      'offers.earlyBird.tag': 'Consigliato',
      'offers.romantic.title': 'Pacchetto romantico',
      'offers.romantic.description': '3 notti + champagne + massaggio per coppia + cena al tramonto.',
      'offers.romantic.price': 'Da €890',
      'offers.romantic.tag': 'Romantico',
      'offers.wellness.title': 'Ritiro wellness',
      'offers.wellness.description': '3 notti + yoga quotidiano + 2 massaggi + colazione sana.',
      'offers.wellness.price': 'Da €750',
      'offers.wellness.tag': 'Wellness',
      'offers.stay5.title': '5 notti, paghi 4',
      'offers.stay5.description': 'Prenota 5 notti in alta stagione (lug-ago) e paghi solo 4.',
      'offers.stay5.price': '1 notte gratis',
      'offers.stay5.tag': 'Miglior offerta',
      'offers.direct.title': 'Bonus prenotazione diretta',
      'offers.direct.description': 'Prenota direttamente sul nostro sito e ricevi un upgrade gratuito + drink di benvenuto.',
      'offers.direct.price': 'Upgrade gratuito',
      'offers.direct.tag': 'Esclusivo',
      'offers.lastMinute.title': 'Offerta last minute',
      'offers.lastMinute.description': 'Prenota entro 7 giorni e ottieni il 15% di sconto (soggetto a disponibilità).',
      'offers.lastMinute.price': '15% di sconto',
      'offers.lastMinute.tag': 'Offerta speciale',

      // Common
      'common.book': 'Prenota',
      'common.learn': 'Scopri di più',
      'common.close': 'Chiudi',
      'common.loading': 'Caricamento...',
      'common.error': 'Errore',
      'common.success': 'Successo',
      'common.from': 'Da',
      'common.perNight': 'a notte',

      // Footer
      'footer.description': 'Hotel boutique di lusso nel cuore di Bled. Una villa storica del 1878 trasformata in un santuario di eleganza.',
      'footer.contact': 'Contatti',
      'footer.links': 'Link rapidi',
      'footer.newsletter.title': 'Newsletter',
      'footer.newsletter.desc': 'Iscriviti alla nostra newsletter per offerte esclusive.',
      'footer.newsletter.placeholder': 'La tua email',
      'footer.newsletter.button': 'Iscriviti',
      'footer.rights': 'Tutti i diritti riservati.',

      // Why Choose Us
      'whyChoose.badge': 'Perché sceglierci',
      'whyChoose.title': 'Perché Villa Adora?',
      'whyChoose.subtitle': 'Scopri cosa ci distingue e perché gli ospiti di tutto il mondo tornano.',
      'whyChoose.bestPrice': 'Miglior prezzo garantito',
      'whyChoose.bestPriceDesc': 'Garantiamo il miglior prezzo. Se trovate un prezzo più basso, lo battiamo del 10%.',
      'whyChoose.heritage': 'Patrimonio storico',
      'whyChoose.heritageDesc': 'Una villa del 1878, ristrutturata con amore per i dettagli e rispetto per la storia.',
      'whyChoose.personalized': 'Servizio personalizzato',
      'whyChoose.personalizedDesc': 'Ogni ospite è speciale per noi. Personalizziamo il vostro soggiorno nei minimi dettagli.',
      'whyChoose.awards': 'Qualità premiata',
      'whyChoose.awardsDesc': 'Riconosciuto da ospiti e esperti di viaggio come uno dei miglior hotel boutique in Slovenia.',
      'whyChoose.concierge': 'Concierge 24/7',
      'whyChoose.conciergeDesc': 'Il nostro concierge digitale Luka è disponibile 24 ore al giorno, 7 giorni su 7.',
      'whyChoose.location': 'Posizione privilegiata',
      'whyChoose.locationDesc': 'Direttamente sul lago di Bled, con viste sull\'isola e sul castello. La migliore posizione a Bled.',
      'whyChoose.stat.rating': 'Valutazione media',
      'whyChoose.stat.reviews': 'Recensioni degli ospiti',
      'whyChoose.stat.established': 'Fondato',
      'whyChoose.stat.returnGuests': 'Ospiti che tornano',

      // Seasons
      'seasons.title': 'Bled attraverso le stagioni',
      'seasons.subtitle': 'Ogni stagione porta la sua magia',
      'seasons.spring.title': 'Primavera',
      'seasons.spring.desc': 'Fiori di ciliegio, giornate calde e un lago tranquillo. Perfetto per kayak e escursioni.',
      'seasons.summer.title': 'Estate',
      'seasons.summer.desc': 'Acqua calda per nuotare, terrazze vivaci e lunghe serate.',
      'seasons.autumn.title': 'Autunno',
      'seasons.autumn.desc': 'Foglie dorate, vini pregiati e mattine nebbiose mistiche.',
      'seasons.winter.title': 'Inverno',
      'seasons.winter.desc': 'Avvolta nella neve, Bled diventa una fiaba. Mercatino di Natale, sci e bevande calde.',

      // Culinary
      'culinary.subtitle': 'Esperienze culinarie',
      'culinary.title': 'Sapori di Bled',
      'culinary.description': 'Scoprite la ricchezza dei sapori locali offerti nel nostro hotel. Dalla tradizionale crema di Bled ai vini sloveni d\'eccellenza.',
      'culinary.breakfast.title': 'Colazione sul lago',
      'culinary.breakfast.description': 'Iniziate la giornata con una ricca colazione a buffet sulla terrazza con vista sul lago.',
      'culinary.restaurant.title': 'Ristorante 1878',
      'culinary.restaurant.description': 'Il nostro ristorante offre un\'interpretazione moderna della cucina slovena con ingredienti locali.',
      'culinary.terrace.title': 'Terrazza sul lago',
      'culinary.terrace.description': 'Godetevi caffè o cena sulla nostra terrazza esclusiva direttamente sul lago.',
      'culinary.experiences.title': 'Laboratori di cucina',
      'culinary.experiences.description': 'Partecipate ai nostri laboratori di cucina — imparate a preparare la crema di Bled, la tradizionale potica o assaggiate i migliori vini sloveni.',
      'culinary.cta': 'Prenota un tavolo',

      // Newsletter
      'newsletter.title': 'Resta in contatto',
      'newsletter.description': 'Iscriviti alla nostra newsletter e ricevi offerte esclusive, pacchetti stagionali e notizie da Villa Adora.',
      'newsletter.placeholder': 'Il tuo indirizzo email',
      'newsletter.button': 'Iscriviti',
      'newsletter.success': 'Grazie per l\'iscrizione!',
      'newsletter.error': 'Inserisci un indirizzo email valido.',
      'newsletter.privacy': 'La tua email sarà utilizzata esclusivamente per la nostra newsletter.',

      // FAQ
      'faq.checkin.question': 'Quali sono gli orari di check-in e check-out?',
      'faq.checkin.answer': 'Il check-in è dalle 15:00 alle 22:00. Il check-out è entro le 11:00. Orari successivi disponibili su richiesta.',
      'faq.cancellation.question': 'Qual è la politica di cancellazione?',
      'faq.cancellation.answer': 'Cancellazione gratuita fino a 48 ore prima dell\'arrivo. Per alta stagione (luglio-agosto) è richiesta con 72 ore di anticipo.',
      'faq.parking.question': 'È disponibile parcheggio gratuito?',
      'faq.parking.answer': 'Sì, un parcheggio privato gratuito è disponibile in loco per tutti gli ospiti.',
      'faq.pets.question': 'Sono ammessi animali domestici?',
      'faq.pets.answer': 'Sì, gli animali domestici sono ammessi su richiesta. Si applica una pulizia aggiuntiva di €30 per soggiorno.',
      'faq.breakfast.question': 'La colazione è inclusa nel prezzo?',
      'faq.breakfast.answer': 'Sì, una ricca colazione a buffet è inclusa nel prezzo della camera. Servita dalle 7:30 alle 10:30 sulla terrazza con vista lago.',
      'faq.airport.question': 'Come arrivo dall\'aeroporto a Villa Adora?',
      'faq.airport.answer': 'L\'aeroporto di Lubiana Jože Pučnik è a 35 km. Offriamo trasferimento su richiesta (€40 a tratta).',
      'faq.wifi.question': 'È disponibile WiFi gratuito?',
      'faq.wifi.answer': 'Sì, WiFi gratuito ad alta velocità è disponibile in tutto l\'hotel e in tutte le suite.',
      'faq.spa.question': 'Avete un centro wellness?',
      'faq.spa.answer': 'Sì, il nostro centro wellness include sauna finnese, bagno turco e servizi di massaggio. L\'accesso è gratuito per tutti gli ospiti.',
      'faq.transport.question': 'Offrite trasporto o noleggio biciclette?',
      'faq.transport.answer': 'Sì, offriamo noleggio gratuito di mountain bike per tutti gli ospiti.',
      'faq.miniBar.question': 'La suite ha un minibar?',
      'faq.miniBar.answer': 'Sì, tutte le suite hanno un minibar con vini sloveni selezionati, bevande e snack.',

      // Virtual Tour
      'virtualTour.lobby.title': 'Lobby e Reception',
      'virtualTour.lobby.description': 'Scopri il grandioso ingresso di Villa Adora con il suo fascino storico.',
      'virtualTour.suite.title': 'Tour della suite di lusso',
      'virtualTour.suite.description': 'Entra nelle nostre suite signature e esplora ogni dettaglio.',
      'virtualTour.lake.title': 'Terrazza con vista lago',
      'virtualTour.lake.description': 'Goditi le mozzafiato viste panoramiche sul lago di Bled.',
      'virtualTour.dining.title': 'Ristorante e cucina',
      'virtualTour.dining.description': 'Scopri il nostro elegante ristorante e l\'esperienza culinaria sul lago.',

      // Book Direct
      'bookDirect.badge': 'Prenota direttamente e risparmia',
      'bookDirect.title': 'Perché prenotare direttamente con noi?',
      'bookDirect.subtitle': 'Salta l\'intermediario e ottieni il miglior valore.',
      'bookDirect.bestPrice.title': 'Miglior prezzo garantito',
      'bookDirect.bestPrice.description': 'Se trovi un prezzo più basso, lo eguagliamo. Più uno sconto aggiuntivo del 5%.',
      'bookDirect.freeBreakfast.title': 'Colazione gratuita',
      'bookDirect.freeBreakfast.description': 'Goditi una ricca colazione gourmet con vista lago — inclusa gratuitamente.',
      'bookDirect.freeWifi.title': 'WiFi Premium',
      'bookDirect.freeWifi.description': 'Internet ad alta velocità in tutto l\'hotel.',
      'bookDirect.upgrade.title': 'Upgrade gratuito',
      'bookDirect.upgrade.description': 'Le prenotazioni dirette ricevono priorità per upgrade gratuiti.',
      'bookDirect.directSupport.title': 'Supporto diretto',
      'bookDirect.directSupport.description': 'Parla direttamente con il nostro team per un servizio personalizzato.',
      'bookDirect.flexible.title': 'Cancellazione flessibile',
      'bookDirect.flexible.description': 'Cancellazione gratuita fino a 48 ore prima dell\'arrivo.',
      'bookDirect.cta': 'Verifica disponibilità',

      // Trust Badges
      'trust.secureBooking': 'Prenotazione sicura',
      'trust.noPrepayment': 'Nessun pagamento anticipato',
      'trust.ssl': 'Crittografia SSL',
      'trust.bestPrice': 'Miglior prezzo',

      // Wellness Preview
      'wellness.sauna.title': 'Sauna finlandese',
      'wellness.sauna.desc': 'Sauna calda con aromi di legno e vista sul lago. Preparatevi per un completo relax.',
      'wellness.turkish.title': 'Bagno turco',
      'wellness.turkish.desc': 'Tradizionale bagno turco. Vapore caldo e purificazione della pelle con vista sul lago.',
      'wellness.massage.title': 'Massaggi',
      'wellness.massage.desc': 'Massaggi professionali — aromaterapia, sportivi e rilassanti. Ogni massaggio è personalizzato.',
      'wellness.relaxation.title': 'Zona relax',
      'wellness.relaxation.desc': 'Uno spazio tranquillo per leggere, meditare e rilassarsi con vista sul lago.',
      'wellness.infinity.title': 'Piscina infinity',
      'wellness.infinity.desc': 'Piscina esterna con vista sul lago e solettaio. Acqua calda tutto l\'anno.',
    },
  }

  const t = (key: string): string => {
    const langTranslations = translations[language]
    return (langTranslations as Record<string, string>)[key] || key
  }

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('villa-adora-language', language)
  }, [language])

  useEffect(() => {
    // Load language preference from localStorage
    const savedLanguage = localStorage.getItem('villa-adora-language') as 'sl' | 'en' | 'de' | 'it'
    if (savedLanguage && ['sl', 'en', 'de', 'it'].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
